name: Test Solutions

on:
  push:
    paths:
      - 'solutions/**'
  pull_request:
    paths:
      - 'solutions/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check how many solution files changed
      id: check_files
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- solutions/)
        echo "Changed solution files:"
        echo "$changed_files"
        count=$(echo "$changed_files" | wc -l)
        echo "count=$count" >> "$GITHUB_ENV"
        echo "changed_files=$changed_files" >> "$GITHUB_ENV"
        if [ "$count" -gt 1 ]; then
          echo "Error: Multiple Solution codes Changed at a time and do not Run Tests"
          exit 1
        fi
        if [ "$count" -eq 0 ]; then
          echo "No solution files changed. Skipping tests."
          exit 0
        fi

    - name: Set language variable
      id: detect_language
      run: |
        file=$(echo "$changed_files")
        echo "Changed file: $file"
        if [[ $file == *.c ]]; then
          echo "language=c" >> "$GITHUB_ENV"
        elif [[ $file == *.cpp ]]; then
          echo "language=cpp" >> "$GITHUB_ENV"
        elif [[ $file == *.java ]]; then
          echo "language=java" >> "$GITHUB_ENV"
        elif [[ $file == *.py ]]; then
          echo "language=python" >> "$GITHUB_ENV"
        else
          echo "Unsupported language"
          exit 1
        fi

    - name: Run tests for C
      if: env.language == 'c'
      run: |
        gcc solutions/solution.c tests/test.c -o test
        ./test

    - name: Run tests for C++
      if: env.language == 'cpp'
      run: |
        g++ solutions/solution.cpp tests/test.cpp -o test
        ./test

    - name: Run tests for Java
      if: env.language == 'java'
      run: |
        javac solutions/solution.java tests/test.java
        java -cp solutions:tests Main

    - name: Run tests for Python
      if: env.language == 'python'
      run: |
        python3 tests/test.py
