name: Test Solutions

on:
  push:
    paths:
      - 'solutions/**'
      - 'tests/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed solution files
      id: changes
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- solutions/)
        echo "$changed_files"
        count=$(echo "$changed_files" | wc -l)
        echo "count=$count" >> $GITHUB_OUTPUT
        echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

    - name: Error for multiple or no files
      if: steps.changes.outputs.count != '1'
      run: |
        echo "Error: Multiple or no solution files changed. Aborting."
        exit 1

    - name: Set language
      id: lang
      run: |
        file="${{ steps.changes.outputs.changed_files }}"
        if [[ "$file" == *".c" ]]; then
          echo "lang=c" >> $GITHUB_OUTPUT
        elif [[ "$file" == *".cpp" ]]; then
          echo "lang=cpp" >> $GITHUB_OUTPUT
        elif [[ "$file" == *".py" ]]; then
          echo "lang=python" >> $GITHUB_OUTPUT
        elif [[ "$file" == *".java" ]]; then
          echo "lang=java" >> $GITHUB_OUTPUT
        else
          echo "Unknown file type"
          exit 1
        fi

    - name: Run C tests
      if: steps.lang.outputs.lang == 'c'
      run: |
        sudo apt update
        sudo apt install -y gcc
        gcc solutions/solution.c tests/test.c -o test_c
        ./test_c

    - name: Run C++ tests
      if: steps.lang.outputs.lang == 'cpp'
      run: |
        sudo apt update
        sudo apt install -y g++
        g++ solutions/solution.cpp tests/test.cpp -o test_cpp
        ./test_cpp

    - name: Run Python tests
      if: steps.lang.outputs.lang == 'python'
      run: |
        python3 tests/test.py

    - name: Run Java tests
      if: steps.lang.outputs.lang == 'java'
      run: |
        javac solutions/solution.java tests/test.java
        java -cp solutions:tests Main
